### ISSUE TITLE
Increase 1,99th percentiles for dp_pitch; add "min", "max" checks

### ISSUE THREAD

**Issue by taldcroft** [sot/validate_states#9]
Based on spurious validation violations caused by lots of maneuvers, increase the dp_pitch 1,99 validation limits to -5.0, +5.0 degrees.  The tails are just caused by the differences during maneuvers; more maneuvers => larger quantile errors.

Also, add (effectively) min/max checks to make sure the errors during maneuvers never exceeds 15 degrees.  This should be possible by adding 0.01% and 99.99% quantiles with a value of 15.0 deg.

**Comment by jeanconn** [comment]
Closing this for now.  The plus and minus 5 violations are gone in #10 .  We ended up not implementing the 0.01% and 99.99% checks because it was ugly in current code, but could come back to this if needed.
